// Originally generated by Lovable; now maintained here (FD-069, FD-073).
import { createMiddleware } from '@tanstack/react-start'
import { getRequest, setResponseStatus } from '@tanstack/react-start/server'
import { createClient, isAuthRetryableFetchError } from '@supabase/supabase-js'
import type { Database } from './types'




function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/**
 * Reject the call with HTTP 401.
 *
 * A plain throw here was serialised by TanStack Start into a normal 200 response
 * with "Unauthorized" in the body, so proxies, monitoring and the browser all saw
 * a success (FD-073). The client still receives the same Error either way.
 */
function unauthorized(reason: string): never {
  setResponseStatus(401);
  throw new Error(`Unauthorized: ${reason}`);
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {

    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      // A server misconfiguration, reported as one rather than as a 200 (FD-073).
      setResponseStatus(500);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      unauthorized('No request headers available');
    }


    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      unauthorized('No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      unauthorized('Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      unauthorized('No token provided');
    }

    if (token.split('.').length !== 3) {
      unauthorized('Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Was getClaims(), which only checks the JWT's signature locally: after Log out
    // the token kept working until it expired, about an hour (FD-069). getUser()
    // asks GoTrue, which also rejects a token whose session has been revoked.
    const { data, error } = await supabase.auth.getUser(token);
    if (error && (isAuthRetryableFetchError(error) || (error.status ?? 0) >= 500)) {
      // GoTrue unreachable or failing is an outage, not a bad token; a 401 here
      // would tell the browser the user had been signed out.
      console.error('[Supabase] Could not reach the auth service to validate a token', error);
      setResponseStatus(503);
      throw new Error('Authentication service unavailable. Please try again.');
    }
    if (error || !data?.user) {
      unauthorized('Invalid or expired session');
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        user: data.user,
      },
    });
  },
);
